#pragma once

#include"all.h"

//deport_port 
#define IOCTL_DIRECT_GET_DEBUG_PORT CTL_CODE(FILE_DEVICE_UNKNOWN,0x810,METHOD_OUT_DIRECT,FILE_WRITE_DATA | FILE_READ_DATA)
NTSTATUS ReadDebugPort(IN PIRP pIrp,ULONG inSize,ULONG outSize);

#define IOCTL_DIRECT_GET_DEBUG_PORT_SET  CTL_CODE(FILE_DEVICE_UNKNOWN,0x811,METHOD_IN_DIRECT,FILE_WRITE_DATA | FILE_READ_DATA)
NTSTATUS ReadDebugPortSet(IN PIRP pIrp,ULONG inSize,ULONG outSize);

